### ISSUE TITLE
Critical bug with scorm packages with client id where domains are not unique

### ISSUE THREAD

**Issue by andrewhancox** [catalyst/moodle-mod_scormremote#72] opened 2024-09-23 09:29 UTC
The client ID is not set on the URL passed to the third layer template, this mean that if you have non-unique customer domains it fails.

**Comment by andrewhancox** [comment] 2024-09-23 09:37
Fix supplied in PR #73

**Comment by bwalkerl** [comment] 2024-09-27 01:10
#73 has been merged.

In the PR I did note that the same issue can be encountered when a user doesn't set a Client ID when creating a wrapper for clients with non unique domains. Our options here are limited since it's optional by design (so that wrappers can be shared with multiple clients), but as part of #70 I've added an option to force the validation (and use) of client ids, and added an additional  text on the wrapper form to increase the visibility.

While not a perfect solution, I don't think we are going to get anything better so I'm going to mark this as finished..

**Closed as completed by bwalkerl** 2024-09-27 01:10 UTC
