### ISSUE TITLE
Not compatible with 3.9

### ISSUE THREAD

**Issue by andrewhancox** [catalyst/moodle-mod_scormremote#61] opened 2024-01-03 10:57 UTC
The MOODLE_39_STABLE is not actually compatible with Moodle 3.9 as it depends on core_files\archive_writer

I've pushed a version that works to https://github.com/andrewhancox/moodle-mod_scormremote/tree/39_compatible

**Comment by leonstr** [comment] 2024-02-14 16:50
Duplicate of [#43](https://github.com/catalyst/moodle-mod_scormremote/issues/43).

**Closed as completed** 2024-11-05 03:39 UTC
